import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";

export default function Layout({ children, page }) {
  return (
    <>
      <Head>
        <title>{page}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="layout">{children}</main>
      <Footer />
    </>
  );
}
